DROP TRIGGER UNIVERSITY.ON_COURSE_DELETE;

CREATE OR REPLACE TRIGGER UNIVERSITY.on_course_delete
BEFORE DELETE ON UNIVERSITY.COURSES FOR EACH ROW
BEGIN
  DELETE FROM enroll WHERE course_id = :OLD.course_id;
END;
/
